### ISSUE TITLE
Problem converting YOLO weights 

### ISSUE THREAD

**Issue by 0000marcosg** [javirk/Person_remover#1]
Hi, 

Im having issues converting the YOLO weights. After downloading the model Im getting this error.

```
python convert.py
Traceback (most recent call last):
File "convert.py", line 4, in <module>
    from yolo.yolov3.models import YoloV3, YoloV3Tiny
    ModuleNotFoundError: No module named 'yolo.yolov3'
```

**Comment by javirk** [comment]
That's because you are running the convert.py program from the folder where it is saved, not from the root directory. Remove the "yolo." from "yolo.yolov3.models" and it will work.
