### ISSUE TITLE
problem in convert.py

### ISSUE THREAD

**Issue by Kunika21** [javirk/Person_remover#4]
Hi, 

when you are converting the yolov3.weights at that time you have given the name yolov3_class.tf but when you are loading, you have called the file as yolov3.tf . And, on first place there is no file getting saved with name tf extention. I got 3 files with ext .tf.index , yolov3_class.tf.data-00000-of-00002 ,yolov3_class.tf.data-00001-of-00002 which one shall i load?

**Comment by javirk** [comment]
Hi,

I have fixed convert.py in master branch. data-0000X-of-0000N files are TF's checkpoint's formatted files that contain the trained weights of the model. Tensorflow uses the .index file to absorb the weights from those data files, but the route should be  'yolov3.tf', without specifying another file extension. https://www.tensorflow.org/tutorials/keras/save_and_load
